apiVersion: v2
name: kubenest
description: Deploy the full KubeNest stack — backend, hub, UI, operator, postgres, redis
type: application
version: 2.0.0
appVersion: "2.0.0"

maintainers:
  - name: Kubenest Team
    email: support@kubenest.io

dependencies:
  - name: postgresql
    version: "16.4.1"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: redis
    version: "20.6.2"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
