apiVersion: v2
name: kubenest
description: Deploy the full KubeNest stack — backend, hub, UI, operator, postgres, redis
type: application
version: 2.1.0
appVersion: "2.1.0"

maintainers:
  - name: Kubenest Team
    email: support@kubenest.io

dependencies:
  - name: postgresql
    version: "18.5.13"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: redis
    version: "25.3.8"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: kubenest-operator-2
    version: "2.0.0"
    repository: "oci://ghcr.io/kubenesthq"
    condition: operator.enabled
    alias: operator-chart

