# Shared configuration
tld: "my-cluster.kubenestapp.com"
email: "admin@example.com"
apiUrl: "https://api.kubenest.io"
apiKey: ""
operatorVersion: "05-04-2025.09.57"

# Operator configuration
operator:
  debug: false
  deleteFailedJobs: true
  imported: true
  image:
    repository: "ghcr.io/kubenesthq/operator"
    pullPolicy: "Always"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Metrics configuration
metrics:
  port: 8443
  service:
    create: true
    type: ClusterIP

# Health probe configuration
healthProbe:
  port: 8081
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10

# Leader election configuration
leaderElection:
  enabled: false

credentials:
  licenseKey: "ABC123"
  licenseEmail: "test@example.com"

serviceAccount:
  name: kubenest-operator
  create: true

# Buildwatch configuration
buildwatchImage:
  repository: "ghcr.io/kubenesthq/buildwatch"
  tag: "07-03-2025.09.50"
  pullPolicy: "Always"
buildwatchConfig:
  inCluster: true
  serverAddress: ":8080"

# Optional components
ingress:
  enabled: true

certManager:
  enabled: true

registry:
  enabled: true
  ingress:
    enabled: false
  persistence:
    enabled: true
    size: "10Gi"
  secrets:
    htpasswd: ""
  updateStrategy:
    type: "Recreate"
