apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    {{- include "kubenest.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: {{ .Release.Name }}
