apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "kubenest.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ required "jwtSecret is required" .Values.jwtSecret | quote }}
  database-url: {{ include "kubenest.database.url" . | quote }}
  admin-email: {{ .Values.backend.admin.email | quote }}
  admin-password: {{ .Values.backend.admin.password | quote }}
